# Generated by Django 5.2.5 on 2025-08-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='tweet',
        ),
    ]
