# Generated by Django 5.2.5 on 2025-08-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_tweet_updated_at_dislike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created_at',
        ),
    ]
